### PR TITLE
setb when debug process running should reply

### PR DESCRIPTION
**Pull request by songtm**
now set/remove breakpoint when debug process is running didn't receive any confirmation. But I'm not sure whether this is compatible with  ZeroBrane Studio IDE or something else

### CODE REVIEW

**Comment by pkulchenko** [comment]
@songtm, is there any particular test or a use case where it breaks something? I need to check my notes on why it's the way it is, but I'm curious why you'd like to change the current behavior...

**Comment by songtm** [comment]
@pkulchenko  For commit a233453. when the server emit "setb" command, there maybe two ways that call "set_breakpoint" function:
- 1.(when lua client suspended)debugger_loop->set_breakpoint
- 2.(when lua client is running)debug_hook->handle_breakpoint->set_breakpoint 

The first way send "200 OK" to the server, while the second way doesn't reply; I think this inconsistency makes the server side code no so clean.
I am working  on a plugin IDEA "emmylua" , and it's hard to produce this problem use the "example" in command line console.

**Comment by songtm** [comment]
@pkulchenko For commit 0b04741.  when use require("mobdebug").loop() is working well.But The "coro_debugee" is nil when use require("mobdebug").start(), so it can't eval vars one the stack frame. 
It's easy to produce , just see the pic below.
qq20180819-164302

**Comment by pkulchenko** [comment]
There is already `200 OK` returned on line 814 after `SETB` command. It shouldn't be returned from `set_breakpoint`, as it's also used for breakpoints set asynchronously and those don't have any responses.

To answer your second question about `eval b --{stack=2}`. The result is a side-effect of not having the main thread identified in Lua 5.1, which doesn't allow to retrieve stack values in that case.

**Pull request closed without merging**
